# Generated by Django 5.2.8 on 2025-11-13 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_images/')),
                ('type_room', models.CharField(choices=[('standart', 'Standart'), ('lux', 'Lux'), ('suite', 'Suite'), ('family', 'Family'), ('single', 'Single'), ('double', 'Double'), ('twin', 'Twin'), ('deluxe', 'Deluxe'), ('presidential', 'Presidential'), ('penthouse', 'Penthouse'), ('cottage', 'Cottage'), ('villa', 'Villa'), ('bungalow', 'Bungalow'), ('hostel', 'Hostel'), ('dormitory', 'Dormitory'), ('capsule', 'Capsule'), ('igloo', 'Igloo'), ('treehouse', 'Treehouse'), ('yurt', 'Yurt'), ('cabin', 'Cabin'), ('chalet', 'Chalet'), ('farmstay', 'Farmstay'), ('glamping', 'Glamping'), ('ryokan', 'Ryokan'), ('pousada', 'Pousada'), ('parador', 'Parador'), ('auberge', 'Auberge'), ('hostal', 'Hostal'), ('motel', 'Motel'), ('inn', 'Inn'), ('guesthouse', 'Guesthouse')], default='standart', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('persons', models.IntegerField(default=1)),
                ('phone_number', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.room')),
            ],
        ),
    ]
